targets:
  $default:
    builders:
      # https://pub.dev/packages/swagger_dart_code_generator#configuration
      swagger_dart_code_generator:
        options:
          input_folder: 'lib/swagger/'
          output_folder: 'lib/generated/'