name: autogram_sign
description: "Autogram service REST API client"
version: 0.2.0
homepage: ""

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chopper: any
  json_annotation: ^4.8.1
  http: any
  basic_utils: ^5.7.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: any
  build_runner: any
  chopper_generator: any
  analyzer: ^6.0.0
  json_serializable: ^6.7.0
  swagger_dart_code_generator: any
