name: autogram_sign
description: "Autogram service REST API client"
version: 0.4.4
homepage: ""

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chopper: ^8.0.0
  json_annotation: 4.9.0
  http:
  basic_utils: ^5.7.0
  intl: '>=0.18.1 <1.0.0'

dev_dependencies:
  lints:
  test:
  build_runner:
  chopper_generator:
  analyzer:
  json_serializable:
  swagger_dart_code_generator:
