name: autogram_sign
description: "Autogram service REST API client"
version: 0.4.1
homepage: ""

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  chopper: '>=7.4.0 <8.0.0'
  json_annotation: 4.9.0
  http: any
  basic_utils: ^5.7.0
  dart_jsonwebtoken: any
  uuid: ^4.3.0
  intl: ^0.18.1

dev_dependencies:
  lints: ^3.0.0
  test: any
  build_runner: any
  chopper_generator: any
  analyzer: ^6.0.0
  json_serializable: ^6.7.0
  swagger_dart_code_generator: any
