name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyze-and-test:
    name: Analyze & test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.3.4

      - name: Install dependencies
        run: dart pub get

      - name: Analyze
        run: dart analyze --fatal-infos

      - name: Run tests
        run: dart test
